spring.application.name=GameVerse
spring.data.mongodb.uri=mongodb+srv://AlandisP:GameVerse2190@gameversecloud.v7arpnu.mongodb.net/gameverse?retryWrites=true&w=majority
server.port=8080
logging.level.org.springframework.data.mongodb=DEBUG
security.jwt.secret-key=561ecf7f164d0f4c9d7dcb74a6c385488a28dfed2f4adad9f8858e14c767cd2c
security.jwt.expiration-time=10800000
aws.accessKeyId=AKIAQMRVSCMDSQ4W7R52
aws.secretKey=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
aws.region=us-east-2
aws.bucketName=gameverse-media-026955879175-us-east-2-an