spring.application.name=GameVerse
spring.data.mongodb.uri=mongodb+srv://AlandisP:GameVerse2190@gameversecloud.v7arpnu.mongodb.net/gameverse?retryWrites=true&w=majority
server.port=8080
logging.level.org.springframework.data.mongodb=DEBUG
security.jwt.secret-key=vPPxP4szscmHEuJ9LThyDYXprY7NL2487EEYoHPnq8GvY2AUJs1DhPssd4hUIyoeTkZYOoY24rHNJIlzvlBcrb
security.jwt.expiration-time=10800000
aws.accessKeyId=AKIAQMRVSCMDS6OOXEEV
aws.secretKey=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
aws.region=us-east-2
aws.bucketName=gameverse-media-026955879175-us-east-2-an

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.connection-timeout=150000